##############################
## @Author : Deepak Tanwar  ##
## @Date :   20210624       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript make_object_from_salmon.R 2> log.stderr > log.stdout
