##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200708       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200708-DGE_analysis_tx.Rmd")' 2> log >> log
