---
title: "ATAC-Seq: Differential analysis volcano plot"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2020-02-13 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: hide
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---

# Library
```{r 20200213-volcano-plot-dif-acc-1, message=FALSE, warning=FALSE}
library(EnhancedVolcano)
library(SummarizedExperiment)
```

# Reading the diff acc data
```{r 20200213-volcano-plot-dif-acc-2, message=FALSE, warning=FALSE}
load("input/atac_diff_chromatin_accessibility.RData")
```

# Table for plotting
```{r 20200213-volcano-plot-dif-acc-3}
tab <- data.frame(rowData(data), stringsAsFactors = F, check.names = F)
tab_lfc <- tab[abs(tab$`diffAccessibility-logFC`) >= 1, ]
tab_fdr <- tab[tab$`diffAccessibility-qvalue` <= 0.05, ]
tab_lfc_fdr <- tab[abs(tab$`diffAccessibility-logFC`) >= 1 & tab$`diffAccessibility-qvalue` <= 0.05, ]
```

# Volcano plot
```{r 20200213-volcano-plot-dif-acc-4}
vp <- EnhancedVolcano(
  toptable = tab,
  lab = tab$`Peak-SYMBOL`,
  selectLab = "",
  x = "diffAccessibility-logFC",
  y = "diffAccessibility-qvalue",
  xlim = c(
    -(ceiling(max(abs(tab$`diffAccessibility-logFC`)))),
    ceiling(max(abs(tab$`diffAccessibility-logFC`)))
  ),
  ylim = c(0, max(-log10(tab$`diffAccessibility-qvalue`), na.rm = TRUE) + 1),
  xlab = bquote(~ Log[2] ~ "fold change (FC)"),
  ylab = bquote(~ -Log[10] ~ adjusted ~ italic(P)),
  pCutoff = 0.05,
  FCcutoff = 1.0,
  labSize = 10.0,
  colAlpha = 0.5,
  legendLabels = c(
    paste("NS"), expression(Log[2] ~ FC),
    adjusted ~ italic(P) - value, expression(adjusted ~ italic(P) - value ~ "&" ~ log[2] ~ FC)
  ),
  legendPosition = "right",
  border = "full",
  legendLabSize = 15.0,
  legendIconSize = 5.0,
  drawConnectors = FALSE,
  title = paste0("Spermatogonial cells: PND15 ", expression(vs), " Adult"),
  subtitle = "",
  captionLabSize = 16
) + theme(plot.title = element_text(hjust = 0.5), legend.text.align = 0)
```


```{r 20200213-volcano-plot-dif-acc-5, fig.align='center', fig.height=8.5, fig.width=11}
vp
```

# Saving results
```{r 20200213-volcano-plot-dif-acc-6}
ggsave(
  filename = "output/20200213-volcano_plot.pdf",
  plot = vp,
  device = "pdf",
  width = 11,
  height = 8.5,
  units = "in"
)
```

# SessionInfo
```{r 20200213-volcano-plot-dif-acc-7}
devtools::session_info()
```
