##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200213       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200213-volcano_plot_dif_acc.Rmd")' 2> log >> log
