##############################
## @Author : Deepak Tanwar  ##
## @Date :   20210705       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("NMF_analysis_union_genes.Rmd")' 2> log.stderr > log.stdout
