---
title: "RNA-Seq: NMF analysis of controls on all genes with FDR <= 0.05 and abs(LFC) >= 1"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2021-07-05 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: show
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries required

```{r, message=FALSE, warning=FALSE}
library(rmarkdown)
library(NMF)
library(viridis)
library(dplyr)
```

# DEA objects and Counts
```{r}
load("./input/limma_SC_Controls_lab_newSeq.RData")
load("./input/data_pData.RData")
data$pData$Group <- factor(data$pData$Group, unique(data$pData$Group)[c(2, 1, 3)])
```


# Data preparation
```{r}
genes <- unique(c(
  dea.limma$`pnd15 vs pnd8`$Genes[dea.limma$`pnd15 vs pnd8`$adj.P.Val <= 0.05 &
    abs(dea.limma$`pnd15 vs pnd8`$logFC) >= 1],
  dea.limma$`pnw21 vs pnd15`$Genes[dea.limma$`pnw21 vs pnd15`$adj.P.Val <= 0.05 &
    abs(dea.limma$`pnw21 vs pnd15`$logFC) >= 1]
))

matrix <- data$cpm[genes, ]
matrix <- matrix + abs(min(matrix))
```


# NMF

## NMF for ranks 2 to 10
```{r}
res.nmf <- NULL
if (file.exists("./output/nmf_SC_controls_fdr05_lfc1.rds")) {
  res.nmf <- readRDS("./output/nmf_SC_controls_fdr05_lfc1.rds")
} else {
  res.nmf <- nmf(x = matrix, rank = 2:10, nrun = 100, seed = 100000, .opt = "vp16")
  saveRDS(res.nmf, "./output/nmf_SC_controls_fdr05_lfc1.rds")
}
```

## Rank and consensus plot
```{r, message=F, warning=F, fig.align='center', fig.height=11, fig.width=8.5}
pdf("./output/SC_control_NMF_rank_plot.pdf", onefile = F, width = 8.5, height = 11)
plot(res.nmf)
dev.off()

pdf("./output/SC_control_NMF_consensus.pdf", onefile = F, width = 8.5, height = 11)
consensusmap(res.nmf, info = T)
dev.off()
```


## Consensus maps for all ranks
```{r}
system("mkdir -p ./output/consensus_heatmap")
system("mkdir -p ./output/coef_basis_plots")

file <- res.nmf

for (i in 2:10) {
  res <- file$fit[[i - 1]]
  consensus.file <- paste0("./output/consensus_heatmap/SC_control_NMF_consensus_rank_", i, ".pdf")

  if (!file.exists(consensus.file)) {
    pdf(consensus.file, width = 11, height = 8.5, onefile = F)
    par(pty = "s")
    consensusmap(
      object = res, col = rocket(100),
      main = paste0("SC controls consensusmap of Rank ", i),
      annCol = data$pData[, c(1:2)], annRow = data$pData[, c(1:2)]
    )
    z <- dev.off()
  }


  bc.file <- paste0("./output/coef_basis_plots/SC_control_NMF_basis_coef_rank_", i, ".pdf")

  if (!file.exists(bc.file)) {
    pdf(bc.file, width = 11, height = 8.5, onefile = F)
    layout(cbind(1, 2))
    basismap(res,
      Rowv = TRUE, subsetRow = T, subsetCol = T,
      color = rocket(100)
    )
    coefmap(res,
      Colv = TRUE, annCol = data$pData[, c(1:2)],
      subsetRow = T, subsetCol = T, color = rocket(100)
    )
    z <- dev.off()
  }
}
```


# References
```{r }
report::cite_packages(session = sessionInfo())
```

# SessionInfo
```{r }
devtools::session_info() %>%
  details::details()
```
