##############################
## @Author : Deepak Tanwar  ##
## @Date :   20201003       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("data_obj_EH.Rmd")' 2> log >> log
