---
title: "Figure2"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2020-07-27 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: hide
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---


# Library
```{r overlap-matrix-rGREAT-1, warning = F, message = F}
library(tidyverse)
library(report)
library(ggpubr)
library(patchwork)
library(viridis)
library(ggfortify)
library(pheatmap)
library(ComplexHeatmap)
library(circlize)
library(readxl)
library(plyr)
library(reshape2)
library(extrafont)
library(ggthemes)
library(EnhancedVolcano)
library(SummarizedExperiment)
library(csaw)
library(edgeR)
library(seriation)
library(ggsci)
ht_opt$message <- FALSE
```


# Data
```{r}
load("input/atac_diff_chromatin_accessibility.RData")
tab <- data.frame(rowData(data), stringsAsFactors = F, check.names = F)
tab_lfc <- tab[abs(tab$`diffAccessibility-logFC`) >= 1, ]
tab_fdr <- tab[tab$`diffAccessibility-qvalue` <= 0.05, ]
tab_lfc_fdr <- tab[abs(tab$`diffAccessibility-logFC`) >= 1 & tab$`diffAccessibility-qvalue` <= 0.05, ]

go_files <- list.files(path = "input", pattern = "ive_GO_BP", full.names = T)
names(go_files) <- gsub(pattern = "input/|\\.xlsx.*|_bg_all.*|_GO.*", replacement = "", x = go_files)

go <- lapply(go_files, function(x) {
  df <- data.frame(read_xlsx(path = x), stringsAsFactors = F, check.names = F)
  df <- df[df$Hyper_Adjp_BH <= 0.05 & df$Total_Genes_Annotated > 50 & df$Total_Genes_Annotated < 1000, ]
  df <- df[order(df$Hyper_Adjp_BH), ][1:20, ]
  return(df[complete.cases(df), ])
})
go_df <- ldply(go, data.frame)
colnames(go_df)[1] <- "Samples_ID"

# go_df$Ontology <- gsub(pattern = ".*_GO_", replacement = "", x = go_df$Samples_ID)
go_df$Group <- trimws(gsub(pattern = "_GO_.*|_|-", replacement = " ", x = go_df$Samples_ID))
# go_df$Hyper_Fold_Enrichment[go_df$Group == "Adult Negative"] <- -(go_df$Hyper_Fold_Enrichment[go_df$Group == "Adult Negative"])

go_files_s <- list.files(path = "input", pattern = "-", full.names = T)
names(go_files_s) <- gsub(pattern = "input/|\\.xlsx.*|_bg_all.*|_GO.*", replacement = "", x = go_files_s)
names(go_files_s) <- gsub(pattern = "intronic_exonic", replacement = "gene_body", x = names(go_files_s))
names(go_files_s) <- gsub(pattern = "Proximal_1000_TSS", replacement = "tss_prox_1kbp", x = names(go_files_s))

go_s <- lapply(go_files_s, function(x) {
  df <- data.frame(read_xlsx(path = x), stringsAsFactors = F, check.names = F)
  df <- df[df$Hyper_Adjp_BH <= 0.05 & df$Total_Genes_Annotated > 50 & df$Total_Genes_Annotated < 1000, ]
  df <- df[order(df$Hyper_Adjp_BH), ][1:20, ]
  return(df[complete.cases(df), ])
})
go_df_s <- ldply(go_s, data.frame)
colnames(go_df_s)[1] <- "Samples_ID"

go_df_s$Group <- trimws(gsub(pattern = "_GO_.*|_|-", replacement = " ", x = go_df_s$Samples_ID))
```

# Colors
```{r}
cols <- magma(n = 10)[c(2, 5, 8)]
cols <- c(PND8 = cols[3], PND15 = cols[2], Adult = cols[1])
```

# Figures

## A
```{r, fig.align='center', fig.height=6, fig.width=8}
th <- theme_bw(base_size = 24) +

  theme(
    legend.background = element_rect(),

    # title, subtitle, and caption
    plot.title = element_text(
      angle = 0,
      size = 18,
      face = "bold",
      vjust = 1
    ),
    plot.subtitle = element_text(
      angle = 0,
      size = 14,
      face = "plain",
      vjust = 1
    ),
    plot.caption = element_text(
      angle = 0,
      size = 14,
      face = "plain",
      vjust = 1
    ),

    # axis text
    axis.text.x = element_text(
      angle = 0,
      size = 16,
      vjust = 1
    ),
    axis.text.y = element_text(
      angle = 0,
      size = 16,
      vjust = 1
    ),
    axis.title = element_text(
      size = 18
    ),

    # legend
    legend.position = "top",
    legend.key = element_blank(),
    legend.key.size = unit(0.5, "cm"),
    legend.text = element_text(
      size = 16
    ),
    title = element_text(
      size = 14
    ),
    legend.title = element_text(size = 18, face = "bold")
  )

legendLabels <- c(
  paste("Not Significant"),
  expression(adjusted ~ italic(P) - 0.05 ~ "&" ~ log[2] ~ -1),
  expression(adjusted ~ italic(P) - 0.05 ~ "&" ~ log[2] ~ 1)
)
```

```{r}
tab$Significant <- "Not Significant"
tab$Significant[tab$`diffAccessibility-qvalue` <= 0.05 & abs(tab$`diffAccessibility-logFC`) >= 1] <- "Negative"
# tab$Significant[tab$`diffAccessibility-qvalue` <= 0.05 & tab$`diffAccessibility-logFC` >= 1] <- "Positive"

tab$Significant[tab$Significant == "Negative"] <- ifelse(tab$`diffAccessibility-logFC`[tab$Significant == "Negative"] > 0, "Positive", "Negative")

tab$Significant[tab$Significant == "Negative"] <- "Low acc. in Adult"
tab$Significant[tab$Significant == "Positive"] <- "High acc. in Adult"

tab$Significant <- factor(x = tab$Significant, levels = unique(tab$Significant)[c(1, 3, 2)])

a <- ggplot(tab, aes(x = `diffAccessibility-logFC`, y = -log10(`diffAccessibility-qvalue`))) +
  geom_point(aes(color = Significant), size = 2, alpha = 0.5) +
  scale_color_manual(values = c("black", "#BC3C29FF", "#0072B5FF")) +
  xlim(
    -(ceiling(max(abs(tab$`diffAccessibility-logFC`)))),
    ceiling(max(abs(tab$`diffAccessibility-logFC`)))
  ) +
  ylim(0, max(-log10(tab$`diffAccessibility-qvalue`), na.rm = TRUE) + 1) +
  xlab(bquote(~ Log[2] ~ "fold change (FC)")) +
  ylab(bquote(~ -Log[10] ~ adjusted ~ italic(P))) +
  labs(
    title = "",
    subtitle = "", caption = paste0("Total = ", nrow(tab), " variables")
  ) +
  th +
  theme(legend.title=element_blank(),
        legend.justification="bottom",
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,-20,0),
        plot.margin=grid::unit(c(1,5,1,1), "mm")) +
  geom_vline(
    xintercept = c(-1, 1),
    linetype = "longdash",
    colour = "black",
    size = 0.4
  ) +
  geom_hline(
    yintercept = -log10(0.05),
    linetype = "longdash",
    colour = "black",
    size = 0.4
  ) +
  guides(
    colour = guide_legend(
      order = 1,
      override.aes = list(
        size = 5
      )
    )
  ) +
  scale_shape_manual(
    values = c(
      `Not Significant` = 19,
      Positive = 19,
      Negative = 19
    ),
    labels = c(
      `Not Significant` = legendLabels[1],
      Positive = legendLabels[3],
      Negative = legendLabels[2]
    )
  )

anno <- data.frame(x = c(-4, 4), y = c(5,5), label = c("n = 760", "n = 2452"), col = c("#BC3C29FF", "#0072B5FF"))

a + geom_label(
    data = anno, aes(x = x, y = y, label = label),
    color = c("#BC3C29FF", "#0072B5FF"),
    size = 5, angle = 45, fontface = "bold"
  )
```



## B

```{r}
rd <- data.frame(rowData(data), check.names = F)
rownames(rd) <- rd$`Peak-Name`
rd <- rd[abs(rd$`diffAccessibility-logFC`) >= 1 & rd$`diffAccessibility-qvalue` <= 0.05, ]
rd$Name <- "Adult Positive"
rd$Name[rd$`diffAccessibility-logFC` < 0] <- "Adult Negative"

rd$Name[rd$Name == "Adult Positive"] <- "High acc. in Adult"
rd$Name[rd$Name == "Adult Negative"] <- "Low acc. in Adult"

rd$anno <- as.character(rd$`Peak-class`)
rd$anno[rd$anno == "intronic" | rd$anno == "exonic"] <- "gene_body"
rd$anno[rd$anno == "TSS" | rd$anno == "proximal <=1000bp"] <- "tss_prox_1kbp"

rd$anno[rd$anno == "gene_body"] <- "Gene body"
rd$anno[rd$anno == "intergenic"] <- "Intergenic"
rd$anno[rd$anno == "tss_prox_1kbp"] <- "TSS & proximal 1kbp"

b <- ggplot(data = rd, mapping = aes(x = anno, fill = anno)) +
  geom_bar(position = "dodge", stat = "count") +
  geom_text(stat = "count", aes(label = ..count..), vjust = -0.1, size = 8) +
  scale_y_continuous(limits = c(0,1100), breaks = c(0,200,400,600,800,1000)) +
  fill_palette(palet = "Dark2") +
  facet_wrap(~Name) +
  ggtitle("") +
  xlab("") +
  ylab("Number of regions") +
  theme_bw() +
  th +
  theme(legend.title = element_blank(),
        axis.text.x  = element_blank(),
        axis.ticks.x = element_blank(),
          legend.justification="bottom",
          legend.margin=margin(0,0,0,0),
          legend.box.margin=margin(0,0,-20,0),
          plot.margin=grid::unit(c(1,5,1,1), "mm"))
  
b
```


## C
```{r}
ont_col <- RColorBrewer::brewer.pal(n = 3, name = "Dark2")

go_df <- go_df %>% map_df(rev)
go_df$name <- factor(go_df$name, levels = go_df$name)

go_df$Group[go_df$Group == "Adult Positive"] <- "High acc. in Adult"
go_df$Group[go_df$Group == "Adult Negative"] <- "Low acc. in Adult"

c <- ggplot(data = go_df, mapping = aes(
  x = name,
  y = Hyper_Fold_Enrichment, color = Hyper_Adjp_BH,
  size = Total_Genes_Annotated
)) +
  geom_point(show.legend = T) +
  coord_flip(expand = T) +
  scale_colour_gradientn(colors = rev(viridis(n = nrow(go_df))), 
                         guide=guide_colorbar(reverse=TRUE), 
                         breaks = c(0.001, 0.02)) +
  xlab("") +
  ylab("Fold enrichment") +
  facet_wrap(~Group, scales = "free_y") +
  th +
  theme(axis.text.y = element_text(size = 12),
        legend.title=element_text(size=14),
          legend.text = element_text(size = 12, angle = 0),
          legend.justification="bottom",
          legend.margin=margin(0,0,0,0),
          legend.box.margin=margin(0,0,-20,0),
        strip.text.x = element_text(size = 12),
          plot.margin=grid::unit(c(1,1,1,1), "mm")) +
  labs(color = expression(bold("adjusted" ~ italic(P)~ " ")),
       size = "Annotated genes")
c
```


## D
```{r}
go_df_s <- go_df_s %>% map_df(rev)
go_df_s$name <- factor(go_df_s$name, levels = unique(go_df_s$name))

go_df_s$Group <- gsub(pattern = "Adult Positive", replacement = "High acc. in Adult", x = go_df_s$Group)
go_df_s$Group <- gsub(pattern = "Adult Negative", replacement = "Low acc. in Adult", x = go_df_s$Group)
go_df_s$Group <- gsub(pattern = "gene_body", replacement = "gene body", x = go_df_s$Group)
go_df_s$Group <- gsub(pattern = "tss prox 1kbp", replacement = "TSS & proximal 1kbp", x = go_df_s$Group)

d <- ggplot(data = subset(go_df_s, Group %in% c("High acc. in Adult TSS & proximal 1kbp", "High acc. in Adult gene body")), mapping = aes(
  x = name,
  y = Hyper_Fold_Enrichment, color = Hyper_Adjp_BH,
  size = Total_Genes_Annotated,
)) +
  geom_point(show.legend = T) +
  coord_flip(expand = T) +
  scale_colour_gradientn(colors = rev(viridis(n = nrow(go_df))), 
                         guide=guide_colorbar(reverse=TRUE), 
                         breaks = c(0.001, 0.03)) +
  xlab("") +
  ylab("Fold enrichment") +
  facet_wrap(~Group, scales = "free_y") +
  th +
  theme(axis.text.y = element_text(size = 12),
        legend.title=element_text(size=14),
          legend.text = element_text(size = 12, angle = 0),
          legend.justification="bottom",
          legend.margin=margin(0,0,0,0),
          legend.box.margin=margin(0,0,-20,0),
        strip.text.x = element_text(size = 12),
          plot.margin=grid::unit(c(1,1,1,1), "mm")) +
  labs(color = expression(bold("adjusted" ~ italic(P)~ " ")),
       size = "Annotated genes")

d
```


# Figure 2
```{r}
ggsave(filename = "output/a.pdf", plot = a, width = 4, height = 4)
ggsave(filename = "output/b.pdf", plot = a, width = 4, height = 4)
ggsave(filename = "output/c.pdf", plot = c, width = 5, height = 6)
ggsave(filename = "output/d.pdf", plot = d, width = 4, height = 8)
```

```{r}
ggsave(filename = "output/a.svg", plot = a, width = 4, height = 4, dpi = 320)
ggsave(filename = "output/b.svg", plot = a, width = 4, height = 4, dpi = 320)
ggsave(filename = "output/c.svg", plot = c, width = 5, height = 6, dpi = 320)
ggsave(filename = "output/d.svg", plot = d, width = 4, height = 8, dpi = 320)
```

# References
```{r overlap-matrix-rGREAT-43 }
report::cite_packages(session = sessionInfo())
```

# SessionInfo
```{r overlap-matrix-rGREAT-44 }
devtools::session_info() %>%
  details::details()
```


<!-- ```{r, eval = F} -->
<!-- y <- asDGEList(data) -->
<!-- colnames(y) <- gsub(".*/|\\..*", "", colData(data)[, 1]) -->
<!-- mat <- cpm(y = y, normalized.lib.sizes = T, log = T) -->
<!-- rownames(mat) <- rowData(data)$`Peak-Name` -->

<!-- rd <- data.frame(rowData(data), check.names = F) -->
<!-- rownames(rd) <- rd$`Peak-Name` -->
<!-- rd <- rd[abs(rd$`diffAccessibility-logFC`) >= 1 & rd$`diffAccessibility-qvalue` <= 0.05, ] -->
<!-- rd$Name <- "Adult Positive" -->
<!-- rd$Name[rd$`diffAccessibility-logFC` < 0] <- "Adult Negative" -->
<!-- rd$anno <- as.character(rd$`Peak-class`) -->
<!-- rd$anno[rd$anno == "intronic" | rd$anno == "exonic"] <- "gene_body" -->
<!-- rd$anno[rd$anno == "TSS" | rd$anno == "proximal <=1000bp"] <- "tss_prox_1kbp" -->

<!-- mat <- mat[rd$`Peak-Name`, ] -->
<!-- mat <- mat - rowMeans(mat[, grep(pattern = "PND15", x = colnames(mat), value = T)]) -->

<!-- o <- seriate(max(mat) - mat, method = "BEA_TSP") -->

<!-- mat <- mat[get_order(o), ] -->

<!-- rd <- rd[rownames(mat), ] -->

<!-- cd <- data.frame(data@colData) -->
<!-- cd$Group <- gsub(pattern = ".*/|_.*", replacement = "", x = cd$bam.files) -->
<!-- cd$Sample <- gsub(pattern = ".*/|\\.bam", replacement = "", x = cd$bam.files) -->
<!-- rownames(cd) <- cd$Sample -->

<!-- col_fun <- colorRamp2(c(-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5), viridis(n = 11)) -->

<!-- HeatmapAnnotation(df = rd[, "anno", drop = FALSE], which = "row") + -->
<!--   Heatmap( -->
<!--     matrix = mat, -->
<!--     col = col_fun, -->
<!--     cluster_rows = F, -->
<!--     # row_order = get_order(o, 1), -->
<!--     # column_order = get_order(o, 2), -->
<!--     cluster_columns = T, -->
<!--     clustering_method_columns = "ward.D", -->
<!--     show_row_names = F, -->
<!--     show_column_names = F, -->
<!--     name = "Enrichment (log)", -->
<!--     row_split = rd$Name, -->
<!--     row_title = NULL, -->
<!--     use_raster = FALSE, -->
<!--     top_annotation = HeatmapAnnotation( -->
<!--       df = cd[, 6, drop = FALSE], -->
<!--       col = list(Group = cols) -->
<!--     ) -->
<!--   ) -->
<!-- ``` -->
