---
title: "Figure6"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2020-07-30 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: hide
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---


# Library
```{r overlap-matrix-rGREAT-1, warning = F, message = F}
library(tidyverse)
library(report)
library(ggpubr)
library(patchwork)
library(viridis)
library(ggfortify)
library(pheatmap)
library(ComplexHeatmap)
library(circlize)
library(readxl)
library(plyr)
library(reshape2)
library(extrafont)
library(ggthemes)
library(EnhancedVolcano)
library(SummarizedExperiment)
library(csaw)
library(edgeR)
library(seriation)
library(ggsci)
ht_opt$message <- FALSE
```


# Colors
```{r}
cols <- magma(n = 10)[c(3, 6, 9)]
cols <- c(PND8 = cols[3], PND15 = cols[2], Adult = cols[1])
```

# Colorbar
```{r}
myPalette <- colorRampPalette(colors = viridis::plasma(n = 7)[c(2, 4, 6)])
```


# Theme
```{r}
th <- theme(
  legend.background = element_rect(),

  # title, subtitle, and caption
  plot.title = element_text(
    angle = 0,
    size = 12,
    face = "bold",
    vjust = 1
  ),
  plot.subtitle = element_text(
    angle = 0,
    size = 10,
    face = "plain",
    vjust = 1
  ),
  plot.caption = element_text(
    angle = 0,
    size = 10,
    face = "plain",
    vjust = 1
  ),

  # axis text
  axis.text.x = element_text(
    angle = 0,
    size = 6,
    # vjust = 0.5
  ),
  axis.text.y = element_text(
    angle = 0,
    size = 6,
    # vjust = 0.5
  ),
  axis.title = element_text(
    size = 8,
    face = "plain",
  ),

  # legend
  legend.position = "top",
  legend.key = element_blank(),
  legend.key.size = unit(0, "cm"),
  legend.text = element_text(
    size = 8,
    margin = margin(r = 0, t = 0, b = 0, l = 0, unit = "pt"),
    vjust = 0.5, hjust = 0.5
  ),
  legend.title = element_text(size = 8, face = "bold", margin = margin(l = 0, unit = "pt")),
  legend.justification = "center",
  legend.margin = margin(c(0, 0, 0, 0)),
  legend.box.margin = margin(0, 0, -7, 0),
  legend.key.height = unit(0, "cm"),
  legend.key.width = unit(0, "cm"),
  legend.spacing = unit(1, "mm"),
  plot.margin = grid::unit(c(1, 1, 1, 1), "mm"),
  strip.background = element_rect(fill = NA, colour = "black"),
  strip.text.x = element_text(face = "bold", size = 8)
)
```



# Data
```{r}
load("input/repeat_elements_atac_diff_chromatin_accessibility.RData")
tab <- data.frame(rowData(data), check.names = F, stringsAsFactors = F)


load("input/data_pData.RData")
load("input/gencode.vM18.anno.RData")

ge <- data.frame(symbol = rownames(data$cpm), data$cpm)
ge_an <- merge(anno[, c(3, 5)], ge)
ge_an <- ge_an[!duplicated(ge_an), ]
re_ele <- subset(ge_an, type %in% c("LTR", "LINE", "SINE"))
re_ele <- re_ele[, c(
  grep(pattern = "symbol|type", x = colnames(re_ele)),
  grep(pattern = "PND15", x = colnames(re_ele)),
  grep(pattern = "Adult", x = colnames(re_ele))
)]
rownames(re_ele) <- re_ele$symbol

pData <- data$pData
```


# Figures
## A
```{r}
tab$Significant <- "Not Significant"
tab$Significant[tab$diffEnrichment.qvalue <= 0.05 & abs(tab$diffEnrichment.logFC) >= 1] <- "Negative"
# tab$Significant[tab$`diffAccessibility-qvalue` <= 0.05 & tab$`diffAccessibility-logFC` >= 1] <- "Positive"

tab$Significant[tab$Significant == "Negative"] <- ifelse(tab$diffEnrichment.logFC[tab$Significant == "Negative"] > 0, "Positive", "Negative")

tab$Significant[tab$Significant == "Negative"] <- "Less acc. in Adult"
tab$Significant[tab$Significant == "Positive"] <- "More acc. in Adult"

tab$Significant <- factor(x = tab$Significant, levels = unique(tab$Significant))

an <- split(x = tab, f = tab$class_id)
an1 <- lapply(an, function(x) {
  return(data.frame(
    x = c(-5, 5),
    y = c(5, 5),
    label = c(
      paste(
        "n =",
        nrow(x[x$diffEnrichment.logFC <= 1 & x$diffEnrichment.qvalue <= 0.05, ])
      ),
      paste(
        "n =",
        nrow(x[x$diffEnrichment.logFC >= 1 & x$diffEnrichment.qvalue <= 0.05, ])
      )
    ),
    col = c("#BC3C29FF", "#0072B5FF")
  ))
})

anno <- ldply(an1, data.frame, .id = "class_id")
anno <- subset(anno, class_id %in% c("LTR", "LINE", "SINE"))


a <- ggplot(subset(tab, class_id %in% c("LTR", "LINE", "SINE")), aes(x = diffEnrichment.logFC, y = -log10(diffEnrichment.qvalue))) +
  geom_point(aes(color = Significant), size = 2, alpha = 0.5) +
  scale_color_manual(values = c("black", "#BC3C29FF", "#0072B5FF")) +
  xlim(
    -(ceiling(max(abs(tab$diffEnrichment.logFC)))),
    ceiling(max(abs(tab$diffEnrichment.logFC)))
  ) +
  ylim(0, max(-log10(tab$diffEnrichment.qvalue), na.rm = TRUE) + 1) +
  xlab(bquote(~ Log[2] ~ "fold change (FC)")) +
  ylab(bquote(~ -Log[10] ~ adjusted ~ italic(P))) +
  labs(
    title = "",
    subtitle = "", caption = paste0("Total = ", scales::comma(nrow(tab)), " tested TEs")
  ) + theme_bw(base_family = "Helvetica") +
  th +
  geom_vline(
    xintercept = c(-1, 1),
    linetype = "longdash",
    colour = "black",
    size = 0.4
  ) +
  geom_hline(
    yintercept = -log10(0.05),
    linetype = "longdash",
    colour = "black",
    size = 0.4
  ) +
  guides(
    colour = guide_legend(
      order = 1,
      override.aes = list(
        size = 4
      )
    )
  ) +
  scale_shape_manual(
    values = c(
      `Not Significant` = 19,
      Positive = 19,
      Negative = 19
    ),
    labels = c(
      `Not Significant` = "Not significant",
      Positive = "More acc. in Adult",
      Negative = "Less acc. in Adult"
    )
  ) +
  facet_wrap(~class_id)

ag <- egg::set_panel_size(p = a, width = unit(5.5, "cm"), height = unit(6, "cm"))
ggsave(plot = ag, filename = "output/a.png", width = unit(8.5, "in"), height = unit(11, "in"))
ggsave(plot = ag, filename = "output/a.pdf", width = unit(8.5, "in"), height = unit(11, "in"))
```



## B

```{r}
rd <- tab
rownames(rd) <- rd$transcript_id
rd <- rd[abs(rd$diffEnrichment.logFC) >= 1 & rd$diffEnrichment.qvalue <= 0.05, ]
rd$Name <- "Adult Positive"
rd$Name[rd$diffEnrichment.logFC < 0] <- "Adult Negative"

rd$Name[rd$Name == "Adult Positive"] <- "More acc. in Adult"
rd$Name[rd$Name == "Adult Negative"] <- "Less acc. in Adult"

rd$anno <- as.character(rd$class)
# rd$anno[rd$anno == "intronic" | rd$anno == "exonic"] <- "gene_body"
rd$anno[rd$anno == "TSS" | rd$anno == "proximal <=1000bp"] <- "tss_prox_1kbp"

rd$anno[rd$anno == "exonic"] <- "Exonic"
rd$anno[rd$anno == "intronic"] <- "Intronic"
rd$anno[rd$anno == "intergenic"] <- "Intergenic"
rd$anno[rd$anno == "tss_prox_1kbp"] <- "TSS +/- 1kbp"

b <- ggplot(data = rd, mapping = aes(x = anno, fill = anno)) +
  geom_bar(position = "dodge", stat = "count") +
  geom_text(stat = "count", aes(label = ..count..), vjust = -0.1, size = 3, fontface = "bold") +
  scale_y_continuous(limits = c(0, 50000), breaks = c(0, 10000, 20000, 30000, 40000, 50000)) +
  fill_palette(palet = "Dark2") +
  # coord_flip() +
  facet_wrap(~Name, nrow = 2) +
  ggtitle("") +
  xlab("") +
  ylab("Number of regions") +
  theme_bw(base_family = "Helvetica") +
  th +
  theme(
    legend.title = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    legend.key.height = unit(0, "mm"),
    legend.key.width = unit(3, "mm"),
    plot.margin = grid::unit(c(0, 0, 0, 0), "mm"),
      legend.text.align = 0
  ) +
  guides(fill = guide_legend(nrow = 2,  byrow = T))

bg <- egg::set_panel_size(p = b, width = unit(4, "cm"), height = unit(4, "cm"))

ggsave(plot = bg, filename = "output/b.pdf", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
```



# C
```{r}
t <- data$cpm[grep(pattern = "Piwi", rownames(data$cpm)), ]
tmp <- data.frame(data$pData, t(t))
tmp <- tmp[order(tmp$Group, decreasing = T), ]

mat <- data.matrix(t(tmp[, 3:ncol(tmp)]))
mat[is.infinite(mat)] <- 0
mat <- data.frame(mat)

median.df <- data.frame(matrix(nrow = nrow(mat), ncol = 3))
rownames(median.df) <- rownames(mat)
colnames(median.df) <- c("PND8", "PND15", "Adult")

median.df$PND8 <- apply(mat[, grep(pattern = "PND8", x = colnames(mat))], 1, median)
median.df$PND15 <- apply(mat[, grep(pattern = "PND15", x = colnames(mat))], 1, median)
median.df$Adult <- apply(mat[, grep(pattern = "Adult", x = colnames(mat))], 1, median)
median.df$Genes <- rownames(median.df)

median.melt <- melt(data = median.df, id.vars = c("Genes"))

piwi <- ggplot(data = median.melt, aes(x = variable, y = value, group = Genes)) +
  geom_line(aes(color = Genes), size = 1, alpha = 1) +
  geom_point(aes(color = Genes), size = 2, alpha = 1) +
  scale_color_brewer(palette = "Dark2") +
  labs(x = "", y = "") +
  scale_y_continuous(limits = c(3.5, 8.5), breaks = c(4, 5, 6, 7, 8)) +
  scale_x_discrete(expand = waiver()) +
  theme_bw(base_family = "Helvetica") +
  th +
  ylab(expression("Median gene expression (" ~ log[2] ~ "CPM )"))

piwi

pg <- egg::set_panel_size(p = piwi, width = unit(4.5, "cm"), height = unit(5.7, "cm"))

ggsave(plot = pg, filename = "output/c.pdf", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
```




## D
```{r}
go_files <- list.files(path = "input", pattern = "ive-", full.names = T)
names(go_files) <- gsub(pattern = "input/|_bg_all_GO_BP.xlsx", replacement = "", x = go_files)

go <- lapply(go_files, function(x) {
  a <- data.frame(readxl::read_xlsx(x), check.names = F, stringsAsFactors = F)
  a <- a[a$Hyper_Adjp_BH <= 0.05, ]
  a <- a[a$Total_Genes_Annotated > 50 & a$Total_Genes_Annotated < 1000, ]
  a <- a[order(a$Hyper_Adjp_BH), ][1:10, ]
  return(a)
})

go_df <- ldply(go, data.frame, .id = "Group")
go_df$Group <- trimws(gsub(pattern = ".*-", replacement = " ", x = go_df$Group))
go_df %>% arrange(Group, Hyper_Fold_Enrichment) -> go_df
go_df <- go_df[-c(10, 30), ]


d <- ggplot(data = go_df, mapping = aes(
  x = fct_inorder(name),
  y = Hyper_Fold_Enrichment, color = Hyper_Adjp_BH,
  size = Total_Genes_Annotated
)) +
  geom_point(show.legend = T, alpha = 0.6) +
  coord_flip(expand = T) +
  scale_colour_gradientn(
    colors = rev(myPalette(n = nrow(go_df))),
    # colors = rev(cividis(n = nrow(go_df))),
    # guide = guide_colorbar(reverse = TRUE),
    breaks = c(round(min(go_df$Hyper_Adjp_BH), 37), round(max(go_df$Hyper_Adjp_BH), 6))
  ) +
  xlab("") +
  ylab("Fold enrichment") +
  facet_wrap(~Group, scales = "free_y", nrow = 3) +
  theme_bw(base_family = "Helvetica") +
  th +
  guides(
    size = guide_legend(title.position = "top", title.hjust = 0.5, title.vjust = 0.5, nrow = 1, size = 8, order = 2),
    colour = guide_colorbar(
      title.position = "top", title.hjust = 0.5, title.vjust = 0.5,
      barwidth = unit(2, "cm"), barheight = unit(0.3, "cm"),
      label.hjust = 0.5, label.vjust = 1, size = 8, order = 1
    )
  ) +
  labs(
    color = expression(bold("adjusted" ~ italic(P) ~ " ")),
    size = "Annotated genes"
  ) +
  theme(legend.margin=margin(0,15,0,0),
        legend.box.margin=margin(0,0,0,0))

d

dg <- egg::set_panel_size(p = d, width = unit(3, "cm"), height = unit(2.1, "cm"))

ggsave(plot = dg, filename = "output/d.pdf", width = unit(8.5, "in"), height = unit(11, "in"), dpi = 320)
```


# References
```{r overlap-matrix-rGREAT-43 }
report::cite_packages(session = sessionInfo())
```

# SessionInfo
```{r overlap-matrix-rGREAT-44 }
devtools::session_info() %>%
  details::details()
```



<!-- ## C -->
<!-- ```{r} -->

<!-- load("input/data_pData_tx.RData") -->

<!-- ge <- data -->
<!-- ge_mat <- data$cpm -->


<!-- load("input/repeat_elements_atac_diff_chromatin_accessibility_gene_level.RData") -->
<!-- ac <- data_ge -->
<!-- ac_mat <- assay(data_ge) -->

<!-- re_ele <- re_ele[grep(pattern = "\\?", x = re_ele$symbol, value = T, invert = T), ] -->
<!-- mat <- re_ele[, 3:ncol(re_ele)] -->
<!-- mat <- data.matrix(mat - rowMeans(mat[, grep(pattern = "PND15", x = colnames(mat), value = T)])) -->

<!-- o <- seriate(max(mat) - mat) -->

<!-- mat <- mat[get_order(o), ] -->

<!-- rd <- re_ele[rownames(mat), 1:2] -->

<!-- cd <- pData[colnames(mat), ] -->
<!-- cd$Group <- factor(cd$Group, levels = unique(cd$Group)) -->

<!-- ele_cols <- RColorBrewer::brewer.pal(n = 3, name = "Dark2") -->
<!-- names(ele_cols) <- c("LINE", "LTR", "SINE") -->

<!-- la <- HeatmapAnnotation( -->
<!--   Category = rd$type, which = "row", -->
<!--   col = list(Category = ele_cols), -->
<!--   simple_anno_size = unit(3, "mm"), -->
<!--   show_annotation_name = TRUE, -->
<!--   annotation_name_side = "bottom", -->
<!--   annotation_legend_param = list( -->
<!--     title_gp = gpar(fontsize = 8, fontface = "bold", fontfamily = "Helvetica"), -->
<!--     labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica") -->
<!--   ), -->
<!--   annotation_name_rot = 0, -->
<!--   annotation_name_gp = gpar(fontsize = 0, fontfamily = "Helvetica") -->
<!-- ) -->

<!-- ha <- HeatmapAnnotation( -->
<!--   df = cd[, 1, drop = FALSE], -->
<!--   col = list(Group = cols[2:3]), -->
<!--   simple_anno_size = unit(3, "mm"), -->
<!--   show_annotation_name = TRUE, -->
<!--   annotation_name_side = "right", -->
<!--   annotation_name_rot = 0, -->
<!--   annotation_name_gp = gpar(fontsize = 0, fontfamily = "Helvetica"), -->
<!--   annotation_legend_param = list( -->
<!--     title_gp = gpar(fontsize = 8, fontface = "bold", fontfamily = "Helvetica"), -->
<!--     labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica") -->
<!--   ) -->
<!-- ) -->

<!-- # col_fun <- colorRamp2(c(-2, 0, 2), viridis(n = 3)) -->
<!-- b <- ha %v% Heatmap( -->
<!--   matrix = mat, -->
<!--   col = viridis(n = 100), -->
<!--   cluster_rows = F, -->
<!--   cluster_columns = T, -->
<!--   clustering_method_columns = "ward.D2", -->
<!--   show_row_names = T, -->
<!--   show_column_names = F, -->
<!--   name = "Enrichment (log)", -->
<!--   row_split = rd$type, -->
<!--   column_split = cd[, 1, drop = FALSE], -->
<!--   cluster_column_slices = TRUE, -->
<!--   column_dend_height = unit(0.5, "cm"), -->
<!--   show_parent_dend_line = FALSE, -->
<!--   row_title = NULL, -->
<!--   top_annotation = ha, -->
<!--   column_title = NULL, -->
<!--   row_names_gp = gpar(fontsize = 8, fontfamily = "Helvetica"), -->
<!--   use_raster = FALSE, -->
<!--   left_annotation = la, -->
<!--   height = unit(x = 5.5, units = "cm"), width = unit(x = 3.5, units = "cm"), -->
<!--   heatmap_legend_param = list( -->
<!--     title = expression(bold(~ Log[2] ~ "fold-change")), -->
<!--     legend_height = unit(2.5, "cm"), -->
<!--     title_position = "leftcenter-rot", -->
<!--     title_gp = gpar(fontsize = 8, fontfamily = "Helvetica"), -->
<!--     labels_gp = gpar(fontsize = 8, fontfamily = "Helvetica") -->
<!--   ) -->
<!-- ) -->

<!-- pdf(file = "output/b.pdf", width = 8.5, height = 11) -->
<!-- draw( -->
<!--   object = b, -->
<!--   heatmap_legend_side = "right", -->
<!--   annotation_legend_side = "right", -->
<!--   merge_legends = TRUE, -->
<!--   align_annotation_legend = "" -->
<!-- ) -->
<!-- dev.off() -->

<!-- # bg <- grid.grabExpr( -->
<!-- #  draw( -->
<!-- #   object = b, -->
<!-- #   heatmap_legend_side = "right", -->
<!-- #   annotation_legend_side = "right", -->
<!-- #   merge_legends = TRUE, -->
<!-- #   align_annotation_legend = "" -->
<!-- # ) -->
<!-- # ) -->
<!-- # -->
<!-- # ggsave(plot = bg, filename = "output/b.png", width = unit(8, "cm"), height = unit(8, "cm"), dpi = 2000) -->
<!-- ``` -->
