##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200910       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200910-RE_comparison.Rmd")' 2> log >> log
