##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190513       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190513-DGE_analysis.Rmd")' 2> log >> log
