##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200911       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("DTE_analysis.Rmd")' 2> log >> log
