---
title: "ATAC-Seq: Softlink files and change names"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2019-10-08 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: show
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries required
```{r 20191008-change-names-files-1, message=FALSE, warning=FALSE}
library(plyr)
```

# Files and desc tables

## Files
```{r 20191008-change-names-files-2}
files1 <- list.files(path = "input", pattern = "_R1.fastq.gz", full.names = TRUE, recursive = TRUE)
files2 <- list.files(path = "input", pattern = "_R2.fastq.gz", full.names = TRUE, recursive = TRUE)
files <- data.frame(Files1 = files1, Files2 = files2, stringsAsFactors = F)
```

## Description file
```{r 20191008-change-names-files-3}
datasets <- list.files(path = "input", pattern = "tsv", full.names = TRUE, recursive = TRUE)
datasets <- lapply(datasets, function(x) read.delim(x,
    header = TRUE,
    stringsAsFactors = FALSE, check.names = FALSE
  ))
datasets <- ldply(datasets, data.frame, stringsAsFactors = FALSE, check.names = FALSE)
```

### Correcting names
```{r 20191008-change-names-files-4}
# Subset
datasets <- datasets[, c(1, 3:5, 7:9, 17, 20, 22)]

# Trim colnames
colnames(datasets) <- trimws(gsub("\\[.*", "", colnames(datasets)))

# Remove location of files
datasets$Files1 <- trimws(gsub(".*very/", "", datasets$Read1))
datasets$Files2 <- trimws(gsub(".*very/", "", datasets$Read2))

# Index for adults and pnd
idx.adults <- which(substr(datasets$Files1, 1, 4) == 2019)
idx.pnd <- which(substr(datasets$Files1, 1, 4) == 2018)

# Adding current location of files
datasets$Files1[idx.adults] <- paste0("input/Adult/", datasets$Files1[idx.adults])
datasets$Files1[idx.pnd] <- paste0("input/PND15/", datasets$Files1[idx.pnd])

datasets$Files2[idx.adults] <- paste0("input/Adult/", datasets$Files2[idx.adults])
datasets$Files2[idx.pnd] <- paste0("input/PND15/", datasets$Files2[idx.pnd])

# Merging files with information
data <- merge(files, datasets)

# Removing location
data$Files1 <- trimws(gsub(".*15/|.*t/", "", data$Files1))
data$Files2 <- trimws(gsub(".*15/|.*t/", "", data$Files2))
idx.adults <- which(substr(data$Files1, 1, 4) == 2019)

# Nex indexes for files
idx.pnd15 <- which(substr(data$Files1, 1, 4) == 2018)

# Adding group information
data$Group <- NA
data$Group[idx.adults] <- "Adult"
data$Group[idx.pnd15] <- "PND15"

# Remove "SSC" from sample IDs
data$Name <- trimws(gsub("SSC", "", data$Name))

# New sample names
data$Samples <- NA
data$Samples[idx.adults] <- paste0(
  "Adult_",
  sprintf(
    "%02d",
    as.numeric(trimws(gsub(
      ".*A-|_.*", "",
      data$Name[idx.adults]
    )))
  )
)
data$Samples[idx.pnd15] <- paste0(
  "PND15_",
  sprintf(
    "%03d",
    as.numeric(trimws(gsub(
      ".*A-|_.*", "",
      data$Name[idx.pnd15]
    )))
  )
)
```

### Full table with runs
```{r 20191008-change-names-files-5}
data.all <- data
readr::write_tsv(data.all, path = "output/dataset.tsv")
```

### Final table to be used
```{r 20191008-change-names-files-6}
data.final <- data[!duplicated(data$Samples), c(13, 14)]
readr::write_tsv(data.final, path = "output/dataset_pnd_adult.tsv")
```

# Creating soft links
```{r 20191008-change-names-files-7}
for (i in 1:nrow(data.all)) {
  cmd1 <- NULL
  cmd2 <- NULL
  if (substr(data.all$Files1[i], 1, 4) == 2019) {
    cmd1 <- paste0("ln -sr ./input/Adult/", data.all$Files1[i], " ./output/", data.all$Samples[i], "_R1.fq.gz")
    cmd2 <- paste0("ln -sr ./input/Adult/", data.all$Files2[i], " ./output/", data.all$Samples[i], "_R2.fq.gz")
  } else {
    cmd1 <- paste0("ln -sr ./input/PND15/", data.all$Files1[i], " ./output/", data.all$Samples[i], "_R1.fq.gz")
    cmd2 <- paste0("ln -sr ./input/PND15/", data.all$Files2[i], " ./output/", data.all$Samples[i], "_R2.fq.gz")
  }
  system(cmd1)
  system(cmd2)
}
```


# SessionInfo
```{r 20191008-change-names-files-8}
devtools::session_info()
```
