##############################
## @Author : Deepak Tanwar  ##
## @Date :   20191008       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20191008-change_names_files.Rmd")' 2> log >> log
