##############################
## @Author : Deepak Tanwar  ##
## @Date :   20211011       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("overlap_matrix.Rmd")' 2> log.stderr > log.stdout
