##############################
## @Author : Deepak Tanwar  ##
## @Date :   20201011       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200910-DTE_analysis.Rmd")' 2> log >> log
