##############################
## @Author : Deepak Tanwar  ##
## @Date :   20191127       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20191118-tfbs_motif_overlap.Rmd")' 2> log >> log
