---
title: "Supplementary table 2"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2020-09-08 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: hide
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---


# Differential analysis results + GSEA analysis from `cameraPR` only GO:BP

# Library
```{r overlap-matrix-rGREAT-1, warning = F, message = F}
library(readxl)
library(writexl)
```


# S1
```{r}
load("input/kmeans_sort_heatmaps_all_dge.RData")

kmeans.new <- kmeans[[4]]$cluster
mat <- mat.sort.clust[[4]]

kmeans.new <- kmeans.new[rownames(mat)]
kmeans.new <- c(
  kmeans.new[kmeans.new == 5],
  kmeans.new[kmeans.new == 3],
  kmeans.new[kmeans.new == 1],
  kmeans.new[kmeans.new == 2],
  kmeans.new[kmeans.new == 4]
)

kmeans.new[kmeans.new == 5] <- "a"
kmeans.new[kmeans.new == 3] <- "b"
kmeans.new[kmeans.new == 1] <- "c"
kmeans.new[kmeans.new == 2] <- "d"
kmeans.new[kmeans.new == 4] <- "e"

kmeans.new[kmeans.new == "a"] <- "cluster 1"
kmeans.new[kmeans.new == "b"] <- "cluster 2"
kmeans.new[kmeans.new == "c"] <- "cluster 3"
kmeans.new[kmeans.new == "d"] <- "cluster 4"
kmeans.new[kmeans.new == "e"] <- "cluster 5"

s1 <- data.frame(Gene_symbol = names(kmeans.new), Cluster = kmeans.new)
```


# S2
```{r}
s2 <- list.files(path = "input", pattern = "xlsx", full.names = T)
names(s2) <- c("cluster 3", "cluster 4", "cluster 2", "cluster 5", "cluster 1")

s2 <- lapply(s2, function(x) {
 a <-  data.frame(read_xlsx(x, sheet = 1))[,-c(6,8)]
 colnames(a) <- c("GO_ID", "GO_name", "Gene_ratio", "Background_ratio", "p-value", "adjusted_p-value", "nGenes")
 a <- a[a$`adjusted_p-value` <= 0.05 & (a$nGenes >= 10 & a$nGenes <= 1000),]
 a <- a[order(a$`adjusted_p-value`),]
  return(a)
})

s2 <- s2[sort(names(s2))]
names(s2) <- paste0("GO ORA - ", names(s2))
```


# Table
```{r}
tabs <- c(
  list(Clusters = s1),
  s2
)

write_xlsx(x = tabs, path = "output/Supplementary_Table_2.xlsx", col_names = T, format_headers = T)
```


# References
```{r overlap-matrix-rGREAT-43 }
report::cite_packages(session = sessionInfo())
```

# SessionInfo
```{r overlap-matrix-rGREAT-44 }
devtools::session_info() %>%
  details::details()
```
