##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190514       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190514-heatmap_common_genes.Rmd")' 2> log >> log
