---
title: "Supplementary table 1"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2020-09-08 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: hide
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---


# Differential analysis results + GSEA analysis from `cameraPR` only GO:BP

# Library
```{r overlap-matrix-rGREAT-1, warning = F, message = F}
library(readxl)
library(writexl)
```


# S1
```{r}
s1 <- data.frame(read_xlsx("input/dea_rnaseq.xlsx", sheet = 1))
colnames(s1) <- c("Gene_symbol", "Transcript_ID", "Gene_ID", "Transcript_biotype", "ENTREZ_Gene_ID", 
                  "Log_fold_change", "Average_gene_expression_CPM_Log2", "t_statistics", "p-value", "adjusted_p-value",
                  "Log_odds")

s1 <- s1[abs(s1$Log_fold_change) >= 1 & s1$`adjusted_p-value` <= 0.05,]
s1 <- s1[order(s1$`adjusted_p-value`),]
```


# S2
```{r}
s2 <- data.frame(read_xlsx("input/dea_rnaseq.xlsx", sheet = 2))
colnames(s2) <- c("Gene_symbol", "Transcript_ID", "Gene_ID", "Transcript_biotype", "ENTREZ_Gene_ID", 
                  "Log_fold_change", "Average_gene_expression_CPM_Log2", "t_statistics", "p-value", "adjusted_p-value",
                  "Log_odds")

s2 <- s2[abs(s2$Log_fold_change) >= 1 & s2$`adjusted_p-value` <= 0.05,]
s2 <- s2[order(s2$`adjusted_p-value`),]
```


# S3
```{r}
s3 <- data.frame(read_xlsx("input/cameraPR_PND8vsPND15_GO_BP.xlsx", sheet = 1))
colnames(s3) <- c("GO_terms", "nGenes", "Direction", "p-value", "t_statistics", "adjusted_p-value")

s3 <- s3[s3$`adjusted_p-value` <= 0.05 & (s3$nGenes >= 10 & s3$nGenes <= 1000),]
s3 <- s3[order(s3$`adjusted_p-value`),]
```

# S4
```{r}
s4 <- data.frame(read_xlsx("input/cameraPR_PND15vsAdult_GO_BP.xlsx", sheet = 1))
colnames(s4) <- c("GO_terms", "nGenes", "Direction", "p-value", "t_statistics", "adjusted_p-value")

s4 <- s4[s4$`adjusted_p-value` <= 0.05 & (s4$nGenes >= 10 & s4$nGenes <= 1000),]
s4 <- s4[order(s4$`adjusted_p-value`),]
```


# Table
```{r}
tabs <- list(
  `DEA - PND8 vs PND15` = s1,
  `DEA - PND15 vs Adult` = s2,
  `GO GSEA - PND8 vs PND15` = s3,
  `GO GSEA - PND15 vs Adult` = s4
)

write_xlsx(x = tabs, path = "output/Supplementary_Table_1.xlsx", col_names = T, format_headers = T)
```


# References
```{r overlap-matrix-rGREAT-43 }
report::cite_packages(session = sessionInfo())
```

# SessionInfo
```{r overlap-matrix-rGREAT-44 }
devtools::session_info() %>%
  details::details()
```
