##############################
## @Author : Deepak Tanwar  ##
## @Date :   20210121       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("overlap_with_id4_peaks.Rmd")' 2> log >> log
