##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200515       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200515_map_peaks_to_genes_heatmap.Rmd")' 2> log >> log
