---
title: "Fragment length distribution"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2020-09-10 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: show
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---


# Library
```{r overlap-matrix-rGREAT-1, warning = F, message = F}
library(ATACseqQC)
```

# BAM files
```{r}
bam_files <- list.files(path = "input", pattern = "bam$", full.names = T)
names(bam_files) <- gsub(pattern = "input/|\\.bam", replacement = "", x = bam_files)
```

# Distribution
```{r}
fragSize <- fragSizeDist(bamFiles = bam_files, bamFiles.labels = names(bam_files))
saveRDS(fragSize, "output/fragSize.rds")
```


# References
```{r overlap-matrix-rGREAT-43 }
report::cite_packages(session = sessionInfo())
```

# SessionInfo
```{r overlap-matrix-rGREAT-44 }
devtools::session_info() %>%
  details::details()
```
