##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200113       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200113-dmrs_analysis.Rmd")' 2> log >> log

# https://support.bioconductor.org/p/116411/
