##############################
## @Author : Deepak Tanwar  ##
## @Date :   20201001       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("enriched_heatmaps_data_overlap.Rmd")' 2> log >> log
