##############################
## @Author : Deepak Tanwar  ##
## @Date :   20210120       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("annotate_id4_peaks.Rmd")' 2> log >> log
