##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200608       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("overlap_matrix_GO.Rmd")' 2> log >> log
