##############################
## @Author : Deepak Tanwar  ##
## @Date :   20191211       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript 20191211-make_object_from_salmon.R 2> log >> log
