##############################
## @Author : Deepak Tanwar  ##
## @Date :   20191217       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20191217_peaks_annotation_other_figs.Rmd")' 2> log >> log
