##############################
## @Author : Deepak Tanwar  ##
## @Date :   20201014       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("figure5.Rmd")' 2> STDERR > STDOUT
