##############################
## @Author : Deepak Tanwar  ##
## @Date :   201900612       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190612-pathway_analysis.Rmd")' 2> log >> log
