##############################
## @Author : Deepak Tanwar  ##
## @Date :   20201005       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("pathways_analysis.Rmd")' > STDOUT 2> STDERR
