##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200107       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("2020-homer.Rmd")' 2> STDERR > STDOUT
