##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200409       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200409-DGE_analysis.Rmd")' 2> log >> log
