##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190820       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript 20190820-make_object_from_salmon.R 2> log >> log
