##############################
## @Author : Deepak Tanwar  ##
## @Date :   20210119       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("differential_acc_analysis.Rmd")' 2> log >> log
