---
title: "Fragment length distribution"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2020-09-10 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: show
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---


# Library
```{r overlap-matrix-rGREAT-1, warning = F, message = F}
library(ATACseqQC)
library(ggplot2)
library(plyr)
library(dplyr)
```

# BAM files
```{r}
bam_files <- list.files(path = "input", pattern = "bam$", full.names = T)
names(bam_files) <- gsub(pattern = "input/|\\.bam", replacement = "", x = bam_files)
```

# Fragment size calculation
```{r}
if (!file.exists("output/fragSize.rds")) {
  fragSize <- fragSizeDist(bamFiles = bam_files, bamFiles.labels = names(bam_files))
  saveRDS(fragSize, "output/fragSize.rds")
} else {
  fragSize <- readRDS("output/fragSize.rds")
}

# fs_df <- lapply(fragSize, function(x) data.frame(x = names(x), y = as.numeric(x)))
# fs_df <- ldply(fs_df, data.frame, .id = "Sample")
```

# Plots
```{r, fig.height=11, fig.width=8.5, fig.align='center'}
par(mfrow = c(4, 3))
for (i in 1:12) {
  plot(fragSize[[i]], main = names(fragSize)[i], xlab = "", ylab = "")
}
```

## NFF
```{r, fig.height=4, fig.width=5, fig.align='center'}
plot(fragSize[[13]], main = names(fragSize)[13], xlab = "", ylab = "")
```


# References
```{r overlap-matrix-rGREAT-43 }
report::cite_packages(session = sessionInfo())
```

# SessionInfo
```{r overlap-matrix-rGREAT-44 }
devtools::session_info() %>%
  details::details()
```
