##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190816       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190816-merge_runs.Rmd")' 2> log >> log
