##############################
## @Author : Deepak Tanwar  ##
## @Date :   20191129       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20191129_map_tfMotifs_to_genes.Rmd")' 2> log >> log
