##############################
## @Author : Deepak Tanwar  ##
## @Date :   20191219       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20191219_putative_enhancers.Rmd")' 2> log >> log
