---
title: "Overlap matrix GO classify"
author: "Deepak Tanwar, Pierre-Luc Germain"
date: "<b>Created on:</b> 2020-06-03 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: hide
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = FALSE)
```

# Library
```{r overlap-matrix-GO-1, warning = F, message = F}
library(dplyr)
library(plgINS)
library(ComplexHeatmap)
```

# Data
```{r overlap-matrix-GO-2 }
load("input/overlap_tables.RData")

list <- lapply(sp_df, function(x) inner_join(mat[, 1:73], x)$SYMBOL)
```

# GO analysis
```{r overlap-matrix-GO-3, message=FALSE, warning=FALSE}
go <- msigdbr::msigdbr("Mus musculus", "C5")
go <- go[which(go$gs_subcat == "BP"), ]
go <- split(go$gene_symbol, go$gs_name)

goc <- goclassify(list, go)
```

# Heatmap
```{r overlap-matrix-GO-4, fig.align='center', fig.width=16.5, fig.height=13}
draw(
  plot.goclassify(goc,
    row_names_gp = gpar(fontsize = 10),
    column_names_gp = gpar(fontsize = 10),
    cluster_columns = TRUE,
    cluster_rows = TRUE,
    # heatmap_legend_param = list(direction = "horizontal"),
    # annotation_legend_param = list(direction = "horizontal")
  ),
  # heatmap_legend_side = "bottom",
  # annotation_legend_side = "bottom"
)
```

# Tables
```{r overlap-matrix-GO-5}
data <- goc
data$lengths <- data.frame(data$lengths)
data <- lapply(data, data.frame)
writexl::write_xlsx(x = data, path = "output/go_results.xlsx", col_names = T, format_headers = T)
```


# SessionInfo
```{r overlap-matrix-GO-6 }
devtools::session_info() %>%
  details::details()
```