---
title: "RNA-Seq: Softlink files and change names"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2019-08-16 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: show
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries required
```{r, message=FALSE, warning=FALSE}
library(plyr)
```

# Files and desc tables

## Files
```{r}
files <- list.files(path = "input", pattern = ".gz", full.names = TRUE, recursive = TRUE)
files <- data.frame(Files = files, stringsAsFactors = F)
```

## Description file
```{r}
datasets <- list.files(path = "input", pattern = "tsv", full.names = TRUE, recursive = TRUE)
datasets <- lapply(datasets, function(x) read.delim(x,
    header = TRUE,
    stringsAsFactors = FALSE, check.names = FALSE
  ))
datasets <- ldply(datasets, data.frame, stringsAsFactors = FALSE, check.names = FALSE)
```

### Correcting names
```{r}
# Subset
datasets <- datasets[, c(3, 4, 6:10, 15, 16)]

# Trim colnames
colnames(datasets) <- trimws(gsub("\\[.*", "", colnames(datasets)))

# Remove location of files
datasets$Files <- trimws(gsub(".*very/", "", datasets$Read1))

# Index for adults and pnd
idx.adults <- which(substr(datasets$Files, 1, 4) == 2019)
idx.pnd <- which(substr(datasets$Files, 1, 4) == 2017)

# Adding current location of files
datasets$Files[idx.adults] <- paste0("input/Adult/", datasets$Files[idx.adults])
datasets$Files[idx.pnd] <- paste0("input/PND/", datasets$Files[idx.pnd])

# Merging files with information
data <- merge(files, datasets)

# Removing location
data$Files <- trimws(gsub(".*D/|.*t/", "", data$Files))
idx.adults <- which(substr(data$Files, 1, 4) == 2019)

# Nex indexes for files
idx.pnd8 <- grep(pattern = "PND7", x = data$Files)
idx.pnd15 <- grep(pattern = "PND14", x = data$Files)

# Adding group information
data$Group <- NA
data$Group[idx.adults] <- "Adult"
data$Group[idx.pnd8] <- "PND8"
data$Group[idx.pnd15] <- "PND15"

# New sample names
data$Samples <- NA
data$Samples[idx.adults] <- paste0(
  "Adult_",
  sprintf(
    "%02d",
    as.numeric(trimws(gsub(
      ".*A-|_.*", "",
      data$Files[idx.adults]
    )))
  )
)
data$Samples[idx.pnd8] <- paste0("PND8_", sprintf(
  "%02d",
  as.numeric(trimws(gsub(
    ".*_C|_p.*|_R.*", "",
    data$Files[idx.pnd8]
  )))
))
data$Samples[idx.pnd15] <- paste0("PND15_", sprintf(
  "%02d",
  as.numeric(
    trimws(gsub(
      ".*_C|_R.*", "",
      data$Files[idx.pnd15]
    ))
  )
))

# As PND8 were sequenced twice, adding that information
data$Run <- NA
data$Run[idx.pnd8] <- "A"
data$Run[grep(pattern = "mRNA", x = data$Files)] <- "B"
```

### Full table with runs
```{r}
data.all <- data
data.all$Name <- gsub(pattern = "_NA", replacement = "", x = paste(data$Samples, data$Run, sep = "_"))

readr::write_tsv(data.all, path = "output/dataset.tsv")
```

### Final table to be used
```{r}
data.final <- data[!duplicated(data$Samples), c(11, 12)]
readr::write_tsv(data.final, path = "output/dataset_pnd_adult.tsv")
```

# Creating soft links
```{r}
for (i in 1:nrow(data.all)) {
  cmd <- NULL
  if (substr(data.all$Files[i], 1, 4) == 2019) {
    cmd <- paste0("ln -sr ./input/Adult/", data.all$Files[i], " ./output/", data.all$Name[i], ".fq.gz")
  } else {
    cmd <- paste0("ln -sr ./input/PND/", data.all$Files[i], " ./output/", data.all$Name[i], ".fq.gz")
  }
  system(cmd)
}
```


# SessionInfo
```{r}
devtools::session_info()
```
