##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190618       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190618-pathways_analysis.Rmd", "html_document")' 2> log >> log
