##############################
## @Author : Deepak Tanwar  ##
## @Date :   2020213       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200213-homer_RE.Rmd")' 2> log >> log
