##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190515       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190515-DGCoE_analysis.Rmd")' 2> log >> log
