##############################
## @Author : Deepak Tanwar  ##
## @Date :   20201022       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("overlap_chip_lit.Rmd")' 2> STDERR >> STDOUT
