---
title: "Supplementary table 4"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2020-09-08 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: hide
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---


# Differential analysis results + GSEA analysis from `cameraPR` only GO:BP

# Library
```{r overlap-matrix-rGREAT-1, warning = F, message = F}
library(readxl)
library(writexl)
```


# S1
```{r}
s1 <- list.files(path = "input", pattern = "txt", full.names = T)
names(s1) <- gsub(pattern = "input/|_homer.txt|_bg_all", replacement = "", x = s1)
names(s1) <- gsub(pattern = "Adult_Negative", replacement = "Less acc. in Adult", x = names(s1))
names(s1) <- gsub(pattern = "Adult_Positive", replacement = "More acc. in Adult", x = names(s1))
names(s1) <- gsub(pattern = "-intergenic", replacement = " Intergenic", x = names(s1))
names(s1) <- gsub(pattern = "-Proximal_1000_TSS", replacement = " TSS abs 1kbp", x = names(s1))
names(s1) <- gsub(pattern = "-intronic_exonic", replacement = " Gene body", x = names(s1))

s1 <- s1[c(5, 1, 7, 3, 8, 4, 6, 2)]


s <- lapply(s1, function(x) {
  s <- read.delim(file = x, header = T, sep = "\t", stringsAsFactors = F, check.names = F)
  colnames(s)[c(1,3,5)] <- c("Motif_name","p-value", "adjusted_p-value")

  s <- s[s$`adjusted_p-value` <= 0.05, ]
  s <- s[order(s$`adjusted_p-value`), ]

  return(s)
})

s1 <- s[lapply(s,nrow) > 0]
```


# Table
```{r}
tabs <- s1

write_xlsx(x = tabs, path = "output/Supplementary_Table_4.xlsx", col_names = T, format_headers = T)
```


# References
```{r overlap-matrix-rGREAT-43 }
report::cite_packages(session = sessionInfo())
```

# SessionInfo
```{r overlap-matrix-rGREAT-44 }
devtools::session_info() %>%
  details::details()
```