##############################
## @Author : Deepak Tanwar  ##
## @Date :   20191211       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20191211-expression_comparison.Rmd")' 2> log >> log
