---
title: "RNA-Seq: Softlink files and change names"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2021-06-16 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: show
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries required
```{r change-names-files-1, message=FALSE, warning=FALSE}
library(plyr)
library(dplyr)
library(readxl)
library(readr)
```

# Files and desc tables

## Files
```{r change-names-files-2}
files <- list.files(
  path = "input", pattern = ".gz",
  full.names = TRUE, recursive = TRUE
)
files <- data.frame(Files = files, stringsAsFactors = F)
```

## Description file
```{r change-names-files-3}
datasets <- list.files(
  path = "input", pattern = "tsv",
  full.names = TRUE, recursive = TRUE
)
datasets <- lapply(datasets, function(x) {
  read.delim(x,
    header = TRUE,
    stringsAsFactors = FALSE, check.names = FALSE
  )
})
datasets <- ldply(datasets, data.frame,
  stringsAsFactors = FALSE,
  check.names = FALSE
)
```

### Correcting names
```{r change-names-files-4}
# Trim colnames
colnames(datasets) <- trimws(gsub("\\[.*", "", colnames(datasets)))
colnames(datasets) <- trimws(gsub(" ", "_", colnames(datasets)))

# Remove location of files
datasets$Files <- trimws(gsub(".*very/", "", datasets$Read1))

# Adding current location of files
datasets$Files <- paste0("input/", datasets$Files)

# Merging files with information
data <- merge(files, datasets)
data <- data[, -c(3, 5, 8:10)]
data$Samples <- gsub(
  pattern = "input/20210610.A-o25067_1_[0-9]+-|_R1.fastq.gz",
  replacement = "", x = data$Files
)

# Removing location
# data$Files <- trimws(gsub(".*D/|.*t/", "", data$Files))

# Metadata from Leo
meta <- data.frame(read_xlsx("input/libraries_summary.xlsx",
  sheet = 1, skip = 9
))[, -c(6, 12)]
colnames(meta) <- gsub(
  pattern = "([\\.]+)",
  replacement = "_", x = colnames(meta)
)
colnames(meta) <- gsub("_$", "", colnames(meta))
meta <- meta[meta$To_be_sequenced == "Yes", ]

meta2 <- data.frame(read_xlsx("input/libraries_summary.xlsx",
  sheet = 2, skip = 5
))[, -c(3, 8, 11, 12, 15, 16)]
colnames(meta2) <- gsub(
  pattern = "([\\.]+)", replacement = "_",
  x = colnames(meta2)
)
colnames(meta2) <- gsub("_$", "", colnames(meta2))
colnames(meta2)[1] <- "Label_Irina"


# Final table
tab <- merge(data, meta)
tab <- merge(tab, meta2, all.x = TRUE)

tab$Group <- NA
tab$Group[tab$Age_Group == "PND7"] <- "PND8"
tab$Group[tab$Age_Group == "PND14"] <- "PND15"
tab$Group[tab$Age_Group == "5 months"] <- "PNW21"

tab$LibPrepBatch <- NA
tab$LibPrepBatch[tab$Group == "PNW21"] <- "B1"
tab$LibPrepBatch[!is.na(tab$Library_Prepared)] <- "B1"
tab$LibPrepBatch[is.na(tab$LibPrepBatch)] <- "B2"


# New sample names
tab$SamplesID <- paste(tab$Group, sprintf("%02d", as.numeric(tab$Samples)),
  tab$LibPrepBatch,
  sep = "_"
)
```

### Full table with runs
```{r change-names-files-5}
data.all <- tab

readr::write_tsv(data.all, file = "output/dataset.tsv")
```

### Final table to be used
```{r change-names-files-6}
data.final <- data.all[, c("Group", "LibPrepBatch", "SamplesID")]
readr::write_tsv(data.final, file = "output/dataset_pnd_adult.tsv")
```

# Creating soft links
```{r change-names-files-7}
for (i in 1:nrow(data.all)) {
  cmd <- paste0(
    "ln -sr ", data.all$Files[i], " ./output/",
    data.all$SamplesID[i], ".fq.gz"
  )
  system(cmd)
}
```

# References
```{r change-names-files-8}
report::cite_packages(sessionInfo())
```

# SessionInfo
```{r change-names-files-9}
devtools::session_info() %>%
  details::details()
```
