##############################
## @Author : Deepak Tanwar  ##
## @Date :   20210624       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("expression_comparison.Rmd")' 2> log.stderr >> log.stdout
