##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200129       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200129-differential_analysis.Rmd")' 2> log >> log
