##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190619       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190619-TFA_analysis.html")' 2> log >> log
