##############################
## @Author : Deepak Tanwar  ##
## @Date :   20210705       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("heatmap_genes_kmeans.Rmd")' 2> log.stderr >> log.stdout
