##############################
## @Author : Deepak Tanwar  ##
## @Date :   20201002       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("re_overlap_atac_rnaseq.Rmd")' 2> STDERR > STDOUT
