---
title: "short RNA-Seq: Softlink files and change names"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2020-03-30 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: show
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries required
```{r 20200330-change-names-files-1, message=FALSE, warning=FALSE}
library(plyr)
```

# Files and desc tables

## Files
```{r 20200330-change-names-files-2}
files <- list.files(path = "input", pattern = ".gz", full.names = TRUE, recursive = TRUE)
files <- files[grep(pattern = "_C", x = files)]
files <- data.frame(Files_loc = files, stringsAsFactors = F)
files$Files <- basename(files$Files_loc)
```

## Description file
```{r 20200330-change-names-files-3}
datasets <- list.files(path = "input", pattern = "tsv", full.names = TRUE, recursive = TRUE)
datasets <- lapply(datasets, function(x) {
  read.delim(x,
    header = TRUE,
    stringsAsFactors = FALSE, check.names = FALSE
  )
})
datasets <- ldply(datasets, data.frame, stringsAsFactors = FALSE, check.names = FALSE)
```

### Correcting names
```{r 20200330-change-names-files-4}
# Subset
datasets <- datasets[, c(1, 3, 4, 6:8, 14, 17, 18)]

# Trim colnames
colnames(datasets) <- trimws(gsub("\\[.*", "", colnames(datasets)))

# Remove location of files
datasets$Files <- trimws(gsub(".*very/", "", datasets$Read1))

# Remove MSUS files
datasets <- datasets[grep(x = datasets$Name, pattern = "_C"), ]

# Merging files with information
data <- merge(files, datasets)


# Indexes for files
idx.pnd8 <- grep(pattern = "PND7", x = data$Files)
idx.pnd15 <- grep(pattern = "PND14", x = data$Files)

# Adding group information
data$Group <- NA
data$Group[idx.pnd8] <- "PND8"
data$Group[idx.pnd15] <- "PND15"

# New sample names
data$Samples <- NA

data$Samples[idx.pnd8] <- paste0("PND8_", sprintf(
  "%02d",
  as.numeric(trimws(gsub(
    ".*_C|_p.*|_R.*", "",
    data$Files[idx.pnd8]
  )))
))

data$Samples[idx.pnd15] <- paste0("PND15_", sprintf(
  "%02d",
  as.numeric(trimws(gsub(
    ".*_C|_p.*|_R.*", "",
    data$Files[idx.pnd15]
  )))
))
```

### Full table with runs
```{r 20200330-change-names-files-5}
data.all <- data

readr::write_tsv(data.all, path = "output/dataset.tsv")
```

# Creating soft links
```{r 20200330-change-names-files-6}
for (i in 1:nrow(data.all)) {
  cmd <- paste0("ln -sr ", data.all$Files_loc[i], " ./output/", data.all$Samples[i], ".fq.gz")
  system(cmd)
}
```


# SessionInfo
```{r 20200330-change-names-files-7}
devtools::session_info()
```
