##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200330       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200330-change_names_files.Rmd")' 2> log >> log
