##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200113       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200113-change_namnes_files.Rmd")' 2> log >> log
