##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190902       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190902-pathways_analysis.Rmd")' 2> log >> log
