##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200529       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200528-euler_plot.Rmd")' 2> log >> log
