##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190618       ##
##############################

## Makefile to compile RMarkdown file to HTML.

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190618-data_explore.Rmd")' 2> log >> log
