---
title: "RNA-Seq: differential expression analysis of controls (literature)"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2021-06-24 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: hide
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries required
```{r, message=FALSE, warning=FALSE}
library(plotly)
library(dplyr)
```


# Data
```{r}
load("input/limma_SC_Controls.RData")
lab <- dea.limma

load("input/limma_SC_Controls_lit.RData")
lit <- dea.limma

load("input/limma_SC_Controls_lab_newSeq.RData")
ns <- dea.limma

df1 <- lab$`PND8 vs PND15`
df2 <- lab$`PND15 vs Adult`
df3 <- lit$`PND7 vs PND14`
df4 <- lit$`PND14 vs Adult`
df5 <- ns$`pnd15 vs pnd8`
df6 <- ns$`pnw21 vs pnd15`


filter_lfc <- function(df){
  df[abs(df$logFC) >= 1 & df$adj.P.Val <= 0.05, ]
}

df1 <- filter_lfc(df1)
df2 <- filter_lfc(df2)
df3 <- filter_lfc(df3)
df4 <- filter_lfc(df4)
df5 <- filter_lfc(df5)
df6 <- filter_lfc(df6)


```

# logFC comparison

## PND7/8 vs PND14/15 {.tabset .tabset-pills}

```{r}
plot_logFC <- function(lfc1, lfc2, n1, n2) {
  library(plotly)
  library(dplyr)
  library(robcor)
  
  rownames(lfc1) <- lfc1$Genes
  rownames(lfc2) <- lfc2$Genes

  l1 <- lfc1[abs(lfc1$logFC) >= 1 & lfc1$adj.P.Val <= 0.05, "Genes"]
  l2 <- lfc2[abs(lfc2$logFC) >= 1 & lfc2$adj.P.Val <= 0.05, "Genes"]
  
  genes <- union(l1, l2)

  dat1 <- lfc1[genes, "logFC"]
  names(dat1) <- rownames(lfc1[genes,])
  
  dat2 <- lfc2[genes, "logFC"]
  names(dat2) <- rownames(lfc2[genes,])
  
  genes <- intersect(names(dat1)[!is.na(dat1)], names(dat2)[!is.na(dat2)])
  
  fit <- lm(dat2[genes] ~ dat1[genes])
  fitr <- MASS::rlm(dat2[genes] ~ dat1[genes])

  df <- data.frame(dat1 = dat1[genes], dat2 = dat2[genes], row.names = genes)
  
  ggplot(data = df, aes(x = dat1, y = dat2)) +
  geom_point(alpha = 0.5) +
  theme_bw() +
   stat_smooth(method=function(formula,data,weights=weight) 
     MASS::rlm(formula, data, weights=weight, method="MM"), fullrange=TRUE,
     color = "red") +
    stat_cor(color = "blue", size = 4, aes(label = ..r.label..)) +
    ggtitle(label = "", subtitle = "") +
    xlab(n1) +
    ylab(n2) +
    ylim(c(min(df), max(df) + 2))+
    theme(axis.title=element_text(size=9))
  
  # plot_ly() %>%
  #   add_trace(x = dat1[genes], y = dat2[genes], mode = "markers", name = "Genes") %>%
  #   add_trace(x = dat1[genes], y = predict(fit), mode = "lines", name = "lm") %>%
  #   add_trace(x = dat1[genes], y = predict(fitr), mode = "lines", name = "rlm") %>%
  #   layout(
  #     xaxis = list(title = n1),
  #     yaxis = list(title = n2)
  #     # title = paste("SC controls logFC:", n1, "and", n2)
  #   )
}
```

### lit: PND14 vs PND7 & old: PND15 vs PND8

```{r, warning=FALSE, message=FALSE}
p1 <- plot_logFC(lfc1 = lab$`PND8 vs PND15`, lfc2 = lit$`PND7 vs PND14`, n1 = "Lab (old): PND15 vs PND8", n2 = "Lit: PND14 vs PND7")
```

### lit: PND14 vs PND7 & new: PND15 vs PND8

```{r, warning=FALSE, message=FALSE}
p2 <- plot_logFC(lfc1 = ns$`pnd15 vs pnd8`, lfc2 = lit$`PND7 vs PND14`, n1 = "Lab (new): PND15 vs PND8", n2 = "Lit: PND14 vs PND7")
```

### old: PND15 vs PND8 and new: PND15 vs PND8

```{r, warning=FALSE, message=FALSE}
p3 <- plot_logFC(lfc1 = ns$`pnd15 vs pnd8`, lfc2 = lab$`PND8 vs PND15`, n1 = "Lab (new): PND15 vs PND8", n2 = "Lab (old): PND15 vs PND8")
```


## lit: PNW8 vs PND14 and old: PNW21 vs PND15

```{r, warning=FALSE, message=FALSE}
p4 <- plot_logFC(lfc1 = lab$`PND15 vs Adult`, lfc2 = lit$`PND14 vs Adult`, n1 = "Lab (old): PNW21 (polyA) vs PND15", n2 = "Lit: PNW8 vs PND14")
```


## lit: PNW8 vs PND14 and new: PNW21 vs PND15

```{r, warning=FALSE, message=FALSE}
p5 <- plot_logFC(lfc1 = ns$`pnw21 vs pnd15`, lfc2 = lit$`PND14 vs Adult`, n1 = "Lab (new): PNW21 (total) vs PND15", n2 = "Lit: PNW8 vs PND14")
```

## old: PNW21 vs PND15 and new: PNW21 vs PND15

```{r, warning=FALSE, message=FALSE}
p6 <- plot_logFC(lfc1 = lab$`PND15 vs Adult`, lfc2 = ns$`pnw21 vs pnd15`, n1 = "Lab (old): PNW21 (polyA) vs PND15", n2 = "Lab (new): PNW21 (total) vs PND15")
```


```{r}
(p1 |p2|p3)/(p4|p5|p6)
```

# References
```{r }
report::cite_packages(session = sessionInfo())
```

# SessionInfo
```{r }
devtools::session_info() %>%
  details::details()
```
