---
title: "RNA-Seq: pathway analysis"
author: "Deepak Tanwar"
date: "<b>Created on:</b> 2019-05-23 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    keep_md: no
    number_sections: no
    fig_width: 8
    fig_height: 8
    fig_caption: true
    df_print: paged
    code_folding: show
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
# bibliography: references.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries required
```{r, message=FALSE, warning=FALSE}
library(EnrichmentBrowser)
library(clusterProfiler)
library(org.Mm.eg.db)
library(DT)
library(data.table)
```


# Data
```{r}
load("./input/kmeans_sortMat_k5.RData")
genes.cluster <- split(x = names(kmeans.new), f = kmeans.new)
names(genes.cluster) <- paste0("cluster", names(genes.cluster))
```

# Pathway analysis

## Function
```{r}
kegg_ORA <- function(genes, org = "mmu") {
  genes <- bitr(geneID = genes, fromType = "SYMBOL", toType = "ENTREZID", drop = T, OrgDb = org.Mm.eg.db)[, 2]
  kk <- data.frame(enrichKEGG(gene = genes, organism = org, qvalueCutoff = 0.05), stringsAsFactors = F)
  mkk <- data.frame(enrichMKEGG(gene = genes, organism = org), stringsAsFactors = F)

  return(list(KEGG = kk, KEGGM = mkk))
}
```

## Analysis
```{r}
res.kegg <- lapply(genes.cluster, function(x) kegg_ORA(genes = x))
```


# Kegg overview
```{r}
kegg <- read.csv("./input/pathways.csv", stringsAsFactors = F)
kegg$PathwayID <- paste0("mmu", as.character(sapply(kegg$Pathways, function(y)
  paste(strsplit(y, "")[[1]][1:5], collapse = ""))))

kegg$Pathway <- as.character(sapply(kegg$Pathways, function(y) {
  a <- strsplit(y, "")[[1]]
  return(paste(a[8:length(a)], collapse = ""))
}))

rownames(kegg) <- kegg$PathwayID
```


## Function to show tables

```{r}
showDT <- function(df) {
  datatable(
    setDF(df),
    rownames = F,
    filter = "top", extensions = c("Buttons", "ColReorder"), options = list(
      pageLength = 10,
      buttons = c("copy", "csv", "excel", "pdf", "print"),
      colReorder = list(realtime = FALSE),
      dom = "fltBip"
    )
  )
}
```

## KEGG results table {.tabset .tabset-pills}

### Cluster1
```{r}
showDT(res.kegg$cluster1$KEGG)
```

### Cluster2
```{r}
showDT(res.kegg$cluster2$KEGG)
```

### Cluster3
```{r}
showDT(res.kegg$cluster3$KEGG)
```

### Cluster4
```{r}
showDT(res.kegg$cluster4$KEGG)
```

### Cluster5
```{r}
showDT(res.kegg$cluster5$KEGG)
```


# Results overview
```{r}
res.overview <- lapply(res.kegg, function(x) {
  a <- rownames(x$KEGG)
  unique(kegg[a, 1])
})
res.overview
```

# SessionInfo
```{r}
devtools::session_info()
```