##############################
## @Author : Deepak Tanwar  ##
## @Date :   20190523       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20190523-pathway_analysis.Rmd")' 2> log >> log
