##############################
## @Author : Deepak Tanwar  ##
## @Date :   20191210       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20191210-dupRadar_analysis.Rmd")' 2> log >> log
