##############################
## @Author : Deepak Tanwar  ##
## @Date :   2020218       ##
##############################

## Makefile to run the analysis

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200218-overlap_diff_RE_diff_acc.Rmd")' 2> log >> log
